import { useAppDispatch, useAppSelector } from '../app/hook'
import { Container, Heading } from '@chakra-ui/react'
import { formAction } from '../app/slice/formSlice'
import AddUserForm from '../container/AddUserForm'
import MyButton from '../components/ButtonForm'
import UserList from '../container/UserList'
import { AddIcon } from "@chakra-ui/icons"
import Head from 'next/head'

export default function Home() {
  const state = useAppSelector(state => state.form)
  const dispatch = useAppDispatch()

  const handelToggleForm = () => {
    dispatch(formAction.showForm())
  }
  return (
    <>
      <Head>
        <title>User management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="8xl" bg="whiteAlpha.300" paddingTop={'16'} >
        <Heading as="h2" size="2xl" textAlign="center">User management</Heading>
        {
          state.toggleFormShow ? <AddUserForm /> :
            <MyButton
              onClick={handelToggleForm}
              width={{ base: "200px", "md": "200px" }}
              marginTop={8}
              leftIcon={<AddIcon />}
              colorScheme='blue'>
              Add new user
            </MyButton>
        }
        <UserList />
      </Container>
    </>
  )
}
